# Generated by Django 4.2.26 on 2025-11-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='社团描述')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('category', models.CharField(choices=[('academic', '学术类'), ('art', '艺术类'), ('sports', '体育类'), ('tech', '科技类'), ('culture', '文化类'), ('volunteer', '志愿类'), ('other', '其他')], default='other', max_length=20, verbose_name='社团类别')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '非活跃'), ('pending', '待审核'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_clubs', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('members', models.ManyToManyField(blank=True, related_name='joined_clubs', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
                'ordering': ['-created_at'],
            },
        ),
    ]
